server:
  port: 5000

spring:
  profiles:
    active: ${profile}
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
---

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(8kthVnMDyLTrqpQ1fJuxOV2ovzVNQFMbBEvav7af9VZfiRQs0AdCvNcXgXizwgj3zP/NGnEseZXL1FnKzt56eg==)
    username: ENC(AJWdvNP4zZGFNQ8XzBfskg==)
    password: ENC(I++AzVGD5wjQlQvLHOgiiA==)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(8kthVnMDyLTrqpQ1fJuxOV2ovzVNQFMbBEvav7af9VZfiRQs0AdCvNcXgXizwgj3zP/NGnEseZXL1FnKzt56eg==)
    username: ENC(AJWdvNP4zZGFNQ8XzBfskg==)
    password: ENC(I++AzVGD5wjQlQvLHOgiiA==)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: update